### ISSUE TITLE
sql error - An exception occurred while executing

### ISSUE THREAD

**Issue by cryptobayza** [cyferconnect/marketplace#3]
Hi i installed but when i open the url in the browser and get routed to
public/index.php/home/
I get the following error? Any help would be welcome
I am running on a vps/ubuntu 16

An exception occurred while executing 'SELECT DISTINCT v0_.id AS id_0, v0_.username AS username_1, v0_.join_token AS join_token_2, v0_.token AS token_3, v0_.join_date AS join_date_4, v0_.last_seen AS last_seen_5, v0_.two_factor AS two_factor_6, v0_.total_feedback AS total_feedback_7, v0_.positive AS positive_8, v0_.neutral AS neutral_9, v0_.negative AS negative_10, v0_.fiat AS fiat_11, v0_.total_sell AS total_sell_12, v0_.verified AS verified_13, v0_.pgp AS pgp_14, v0_.fingerprint AS fingerprint_15, v0_.tac AS tac_16, v0_.profile AS profile_17, v0_.btcpublic AS btcpublic_18, v0_.xmraddress AS xmraddress_19, v0_.zecaddress AS zecaddress_20, v0_.profile_image AS profile_image_21, v0_.experience AS experience_22, v0_.level AS level_23, v0_.hd_level AS hd_level_24 FROM vendor_profile v0_ LEFT JOIN listing l1_ ON (v0_.username = l1_.username) ORDER BY v0_.id DESC LIMIT 4':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cyfer.vendor_profile' doesn't exist

**Comment by cryptobayza** [comment]
The database is empty. When i run the composer it throws no errors

**Comment by calmdesert** [comment]
Symfony requires you to create the database and tables.
Login to your dbms and create the database cyfer. Then go to the root directory where the marketplace files are and run

``php bin/console doctrine:schema:update --force``

**Comment by cryptobayza** [comment]
I thanks that worked
