### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by cryptobayza** [cyferconnect/marketplace#4]
Hi I am now stuck when i try to create the admin user i get this: from the apache error log and the server just returns. 
P.S the server is in prod mode
The server returned a "500 Internal Server Error".

2018-07-26T13:53:45+02:00 [critical] Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, role, password, pin, banned, recover, seen_recover) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "admin", "$2y$13$GWmioAKFRG1I3\/aN0LkHrev5pKFlPKkFxS2nBt3vSOq7WvS", 1234, 0, null, 0]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'recover' cannot be null" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 122

**Comment by otriv** [comment]
You likely have a problem with generating a random string on your server with openssl_random_pseudo_bytes. Make sure you have php7.2-mcrypt installed, also put it in dev and see if an error is thrown with openssl_random_pseudo_bytes as an undefined function.

You can take a look here for install mcrypt for 7.2: https://stackoverflow.com/a/48799336

**Comment by cryptobayza** [comment]
I still could not create the admin so i created the admin account using phpmyadmin.
below is what i installed to get where i am now
What got me was i thought apache was using php7.2 but only when checking through a webpage did i notice it was still using 7.0. 
add that to info.php and open in your browser to see your version of php
<?php
phpinfo() 
?>

apt-get install python-software-properties
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php7.2 php7.2-xml php7.2-mysql php7.2-mbstring php7.2-gmp php7.2-json php7.2-dev php7.2-curl php7.2-bcmath php7.2-gd  php7.2-zip
sudo apt-get purge php7.0-common
sudo apt-get -y install gcc make autoconf libc-dev pkg-config
 sudo apt-get -y install libmcrypt-dev
 sudo pecl install mcrypt-1.0.1
When you are shown the prompt

 libmcrypt prefix? [autodetect] :
Press [Enter] to autodetect.

After success installing mcrypt trought pecl, you should add mcrypt.so extension to php.ini.

check its installed
php -i | grep "mcrypt"
----------------
apt-get install libgpgme11-dev
pecl install gnupg
add gnupg.so extension to php
php -i | grep "gnupg"
